# Generated by Django 4.2.16 on 2024-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
